services:
  ytdlp-test:
    build: .
    ports:
      - "8090:8090"
    environment:
      - PORT=8090
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Optional: mount a volume for temporary files
      - ytdlp-temp:/tmp/ytdlp-downloads
    networks:
      - ytdlp-network

volumes:
  ytdlp-temp:

networks:
  ytdlp-network:
    driver: bridge
