apiVersion: apps/v1
kind: Deployment
metadata:
  name: ytdlp-test
  namespace: ytdlp-namespace
  labels:
    app: ytdlp-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ytdlp-test
  template:
    metadata:
      labels:
        app: ytdlp-test
    spec:
      containers:
      - name: ytdlp-test
        image: rg.fr-par.scw.cloud/ytdlp-registry/ytdlp-test:latest
        ports:
        - containerPort: 8090
        env:
        - name: PORT
          value: "8090"
        - name: FLASK_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 5
          periodSeconds: 5
