apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ytdlp-test-hpa-custom
  namespace: ytdlp-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ytdlp-test
  minReplicas: 1
  maxReplicas: 15
  metrics:
    # Scale based on CPU (primary metric)
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    # Scale based on memory
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
  # Custom metric: HTTP requests per second (if you implement it)
  # - type: Pods
  #   pods:
  #     metric:
  #       name: http_requests_per_second
  #     target:
  #       type: AverageValue
  #       averageValue: "10"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300 # Wait 5 minutes before scaling down
      policies:
        - type: Percent
          value: 25 # Scale down by max 25% at a time
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 30 # Quick scale up for downloads
      policies:
        - type: Percent
          value: 200 # Scale up by max 200% at a time
          periodSeconds: 30
        - type: Pods
          value: 3 # Or add max 3 pods at a time
          periodSeconds: 30
      selectPolicy: Max
