apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: ytdlp-test-vpa
  namespace: ytdlp-namespace
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ytdlp-test
  updatePolicy:
    updateMode: "Auto" # Can be "Off", "Initial", or "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: ytdlp-test
        maxAllowed:
          cpu: 2
          memory: 2Gi
        minAllowed:
          cpu: 100m
          memory: 128Mi
        controlledResources: ["cpu", "memory"]
